export const contextId = require('raw!../reports/context_id.txt').trim()
export const dataProjects = require('raw!../reports/projects.txt').trim()
export const dataAccounts = require('raw!../reports/accounts.txt').trim()
export const dataDepartments = require('raw!../reports/departments.txt').trim()
export const dataLedger = require('raw!../reports/aggregated.txt').trim()
export const dataBudget = require('raw!../reports/budget.txt').trim()
