name: Build gh-pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "skjemaer/**"
      - "okolinks/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GhostScript for image generation
        run: |
          sudo apt-get update
          sudo apt-get install ghostscript -y
      - uses: actions/checkout@v2
      # See https://askubuntu.com/a/1081907
      - name: Remove policies for ImageMagic to be able to convert PDFs
        run: sudo rm /etc/ImageMagick-*/policy.xml
      - run: |
          git fetch --no-tags --prune --progress --depth=1 origin gh-pages
          git worktree add dist gh-pages
      - name: Build dist
        run: ./create-web.sh
      - name: Update gh-pages branch
        run: |
          git config --global user.email "okonomi+github@cyb.no"
          git config --global user.name "GitHub"
          git commit -am "Update gh-pages"
          git push -f
        working-directory: ./dist
